name: mmdocir_evaluation
raw_dir: ${MMDOCIR_EVALUATION_ROOT}
interim_dir: ${MMDOC_RAG_DATA_ROOT}/interim/mmdocir_evaluation
processed_dir: ${MMDOC_RAG_DATA_ROOT}/processed/mmdocir_evaluation
language: mixed
role: main_retrieval
